In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/customer_churn.csv")

In [3]:
df.head(8)

,Customer_ID,Product_ID,Transaction_ID,Purchase_Frequency,Average_Order_Value,Most_Frequent_Category,Time_Between_Purchases,Region,Churn_Probability,Lifetime_Value,Launch_Date,Peak_Sales_Date,Season,Preferred_Purchase_Times,Retention_Strategy
0,CUST_9HOS83,PROD_IK97D1,TRANS_II1DZG,17,172.57,Electronics,45,South America,0.98,952.81,2020-03-14,2023-09-11,Winter,Afternoon,Loyalty Program
1,CUST_AJU17N,PROD_UNN7KP,TRANS_9HJF7I,10,64.89,Clothing,6,South America,0.66,5427.51,2022-10-15,2023-01-02,Spring,Afternoon,Discount
2,CUST_11XNYF,PROD_0XEW2W,TRANS_OT96OM,3,120.38,Sports,23,Asia,0.60,3994.80,2021-11-30,2023-04-06,Winter,Evening,Loyalty Program
3,CUST_IGH8G3,PROD_3IIAJN,TRANS_45V00G,12,70.34,Clothing,5,North America,0.78,4880.01,2022-03-20,2023-03-23,Spring,Evening,Discount
4,CUST_OK6PUM,PROD_VMIWD2,TRANS_ZAK760,18,42.39,Electronics,10,North America,0.52,8557.70,2022-11-09,2023-10-28,Spring,Morning,Discount
5,CUST_63F5GB,PROD_L0NAD5,TRANS_HI4MBV,12,132.90,Electronics,42,Europe,0.25,8215.33,2020-12-26,2023-12-09,Winter,Evening,Loyalty Program
6,CUST_P9K9F2,PROD_CVVCB0,TRANS_X0MXCI,16,128.43,Clothing,38,Europe,0.94,7031.07,2022-03-15,2023-09-06,Summer,Afternoon,Email Campaign
7,CUST_EMHZQV,PROD_PVOV5L,TRANS_9B8B46,10,67.52,Electronics,56,Asia,0.56,5167.16,2021-02-17,2023-06-12,Summer,Afternoon,Discount

The goal this week is to 
1.Load dataset
2.inspect columns
3.understand customer variables
4.identify missing values
5.understand target variable(churn)

In [4]:
df.tail(10)

,Customer_ID,Product_ID,Transaction_ID,Purchase_Frequency,Average_Order_Value,Most_Frequent_Category,Time_Between_Purchases,Region,Churn_Probability,Lifetime_Value,Launch_Date,Peak_Sales_Date,Season,Preferred_Purchase_Times,Retention_Strategy
9990,CUST_YS62WF,PROD_XWOHK5,TRANS_OYHBTJ,3,160.03,Home,86,Asia,0.97,3836.21,2022-07-04,2023-02-24,Spring,Morning,Email Campaign
9991,CUST_0HGSIM,PROD_IRMPBR,TRANS_O6T8X2,8,116.37,Sports,73,South America,0.98,325.87,2022-07-09,2023-05-25,Winter,Afternoon,Loyalty Program
9992,CUST_LRGIIG,PROD_ZHK3A0,TRANS_0FGK18,6,131.72,Sports,6,Europe,0.22,8260.91,2021-07-01,2023-01-08,Spring,Evening,Discount
9993,CUST_EQM9Y4,PROD_K3Y4BL,TRANS_STZEZO,17,41.78,Electronics,68,South America,0.49,4006.52,2021-08-08,2023-02-17,Winter,Afternoon,Email Campaign
9994,CUST_929WCK,PROD_PQ6AF5,TRANS_L2CSF0,14,169.43,Electronics,68,South America,0.86,7160.70,2020-10-03,2023-10-08,Spring,Morning,Email Campaign
9995,CUST_BIH0QW,PROD_AAPCHD,TRANS_EP2EGL,15,162.51,Clothing,72,Europe,0.84,1154.61,2022-03-04,2023-02-10,Winter,Evening,Loyalty Program
9996,CUST_DWJAD2,PROD_XWJQE5,TRANS_X7OPB7,18,63.02,Clothing,68,Europe,0.03,593.22,2021-08-21,2023-02-06,Spring,Morning,Loyalty Program
9997,CUST_43HBYL,PROD_PL3BU5,TRANS_VSZM3Y,15,116.80,Home,72,Asia,0.61,4676.35,2020-09-13,2023-05-05,Spring,Evening,Discount
9998,CUST_0SX4MD,PROD_X5O49V,TRANS_B2YCHY,12,144.21,Electronics,38,North America,0.05,6850.85,2020-01-26,2023-08-03,Summer,Morning,Discount
9999,CUST_U1AP5I,PROD_CTS1GQ,TRANS_IBPVC5,3,91.32,Electronics,6,Europe,0.67,1549.00,2021-04-17,2023-01-25,Fall,Morning,Discount

There are 10,000 entries
Now I want to understand the data types of each column

In [5]:
df.dtypes

Customer_ID                     str
Product_ID                      str
Transaction_ID                  str
Purchase_Frequency            int64
Average_Order_Value         float64
Most_Frequent_Category          str
Time_Between_Purchases        int64
Region                          str
Churn_Probability           float64
Lifetime_Value              float64
Launch_Date                     str
Peak_Sales_Date                 str
Season                          str
Preferred_Purchase_Times        str
Retention_Strategy              str
dtype: object

Most of our data types are string
This is good and bad.
Launch_Date and _Sales_Date should be datetime
String means data is beign interpreted as text rather than as numbers, dates,booleans or categories.thiis is often normal and common in real worl business cases, esp customer & ops data.
Sometimes a number may be interpreted as a string. In this case:(Launch_Date and Peak_Sales_Date)  are dates  that have been captured as string.

Common causes:

Cause	                      Example
CSV formatting issues	      commas, spaces, symbols
Mixed values in a column	  numbers + words
Missing values	              "N/A" or blank
Currency symbols	          "KES 1,200"
Percent signs	              "45%"
Dates not standardized	      "12/05/2026"
Human-entered data	          inconsistent formatting

Advantanges:
1. Rich Behavioral/Qualitative Information(This can reveal behavioral patterns.)
this is VERY valuable in:
customer analytics
behavioral analysis
segmentation
sentiment analysis

2.Useful for Segmentation
String columns are excellent for:
clustering customer types
identifying patterns
cohort analysis
customer journey mapping

3.Useful for NLP Later
Text data enables future expansion into:
sentiment analysis
topic modeling
customer feedback analytics
review analysis

Disadvantages
1.Models Cannot Directly Use Strings
Machine learning models require numerical input. model.fit(X, y)
We will encode them first.

2.Hidden Data Quality Problems
String columns often hide:
Hidden Issue	                  Example
inconsistent capitalization	      Male vs male
spelling errors	                  Nairobi vs Nairob
trailing spaces	                  "Yes "
mixed formatting	              "KES1200" vs "1200"
duplicate categories	          "Mobile-App" vs "Mobile App"

3.Memory Inefficiency
Strings consume much more memory than numeric types.
Large datasets become:
slower
heavier
less efficient

4.Slower Computation
Operations on strings are slower than numerical operations.
This matters for:
large datasets
dashboards
ML pipelines
forecasting systems

5.Statistical Analysis Becomes Harder
I cannot directly compute:
averages
correlations
distributions
regressions
e.g df.mean()

6.Risk of False Numerical Interpretation
e.g 100 looks numeric but behaves as text. it may cause "100"+"50"=10050 instead of 150 for dates then:

sorting may fail
time-series analysis breaks
forecasting becomes unreliable 

I will convert when required

After inspection: there is no need to clean the strings 
df['Column'].str.strip()

In [6]:
df['Region'] = df['Region'].str.lower()
df['Preferred_Purchase_Times'] = df['Preferred_Purchase_Times'].str.lower()
df['Season'] = df['Season'].str.lower()
df['Retention_Strategy'] = df['Retention_Strategy'].str.lower()
df['Most_Frequent_Category'] = df['Most_Frequent_Category'].str.lower()

In [7]:
df.head()

,Customer_ID,Product_ID,Transaction_ID,Purchase_Frequency,Average_Order_Value,Most_Frequent_Category,Time_Between_Purchases,Region,Churn_Probability,Lifetime_Value,Launch_Date,Peak_Sales_Date,Season,Preferred_Purchase_Times,Retention_Strategy
0,CUST_9HOS83,PROD_IK97D1,TRANS_II1DZG,17,172.57,electronics,45,south america,0.98,952.81,2020-03-14,2023-09-11,winter,afternoon,loyalty program
1,CUST_AJU17N,PROD_UNN7KP,TRANS_9HJF7I,10,64.89,clothing,6,south america,0.66,5427.51,2022-10-15,2023-01-02,spring,afternoon,discount
2,CUST_11XNYF,PROD_0XEW2W,TRANS_OT96OM,3,120.38,sports,23,asia,0.60,3994.80,2021-11-30,2023-04-06,winter,evening,loyalty program
3,CUST_IGH8G3,PROD_3IIAJN,TRANS_45V00G,12,70.34,clothing,5,north america,0.78,4880.01,2022-03-20,2023-03-23,spring,evening,discount
4,CUST_OK6PUM,PROD_VMIWD2,TRANS_ZAK760,18,42.39,electronics,10,north america,0.52,8557.70,2022-11-09,2023-10-28,spring,morning,discount

In [8]:
df['Launch_Date'] = pd.to_datetime(df['Launch_Date'])
df['Peak_Sales_Date'] = pd.to_datetime(df['Peak_Sales_Date'])

In [9]:
df.dtypes

Customer_ID                            str
Product_ID                             str
Transaction_ID                         str
Purchase_Frequency                   int64
Average_Order_Value                float64
Most_Frequent_Category                 str
Time_Between_Purchases               int64
Region                                 str
Churn_Probability                  float64
Lifetime_Value                     float64
Launch_Date                 datetime64[us]
Peak_Sales_Date             datetime64[us]
Season                                 str
Preferred_Purchase_Times               str
Retention_Strategy                     str
dtype: object

I think Most_Frequent_Category,should be categories. So i will convert them.

In [10]:
df['Most_Frequent_Category']=df['Most_Frequent_Category'].astype('category')
df['Season']=df['Season'].astype('category')
df['Region']=df['Region'].astype('category')
df['Product_ID']=df['Product_ID'].astype('category')
df['Preferred_Purchase_Times']=df['Preferred_Purchase_Times'].astype('category')
df['Retention_Strategy']=df['Retention_Strategy'].astype('category')

In [11]:
df.dtypes

Customer_ID                            str
Product_ID                        category
Transaction_ID                         str
Purchase_Frequency                   int64
Average_Order_Value                float64
Most_Frequent_Category            category
Time_Between_Purchases               int64
Region                            category
Churn_Probability                  float64
Lifetime_Value                     float64
Launch_Date                 datetime64[us]
Peak_Sales_Date             datetime64[us]
Season                            category
Preferred_Purchase_Times          category
Retention_Strategy                category
dtype: object

Now I want to see the technical summary

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               10000 non-null  str
 1   Product_ID                10000 non-null  category
 2   Transaction_ID            10000 non-null  str
 3   Purchase_Frequency        10000 non-null  int64
 4   Average_Order_Value       10000 non-null  float64
 5   Most_Frequent_Category    10000 non-null  category
 6   Time_Between_Purchases    10000 non-null  int64
 7   Region                    10000 non-null  category
 8   Churn_Probability         10000 non-null  float64
 9   Lifetime_Value            10000 non-null  float64
 10  Launch_Date               10000 non-null  datetime64[us]
 11  Peak_Sales_Date           10000 non-null  datetime64[us]
 12  Season                    10000 non-null  category
 13  Preferred_Purchase_Times  10000 non-null  category
 14  Retention_Strategy        10000 non-null  category
dtypes: category(6), datetime64[us](2), float64(3), int64(2), str(2)
memory usage: 850.0 KB

There are no missig values....this is usually very nice but rare. You will mostly find either crrupted data or missing data

Next I will be analysing:
behavioral signals
lifecycle signals
engagement signals
risk (churn) signals
value signals

This is what powers:

churn prediction models
retention strategy
customer segmentation
pricing decisions

I have:
Identity
Customer_ID
Product_ID
Transaction_ID

Behavior
Purchase_Frequency
Time_Between_Purchases
Preferred_Purchase_Times
Most_Frequent_Category

Value
Average_Order_Value
Lifetime_Value
Risk Target
Churn_Probability (target-ish)
Retention_Strategy (label/insight)

Time
Launch_Date
Peak_Sales_Date